version: "3.5"

services:

  sui-auto-updater:
    image: ghcr.io/carbonique/sui-auto-updater:1.0.1
    volumes:
      - web:/config
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

  sui-web:
    image: ghcr.io/carbonique/sui:1.0.0
    ports:
      - "4000:80"
    volumes:
      - web:/app/dashboard

volumes:
  web:
