version: "3.5"

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
    networks:
      - proxy

  sui-auto-discovery:
    image: ghcr.io/carbonique/sui-auto-discovery:1.1.1
    environment:
      DOCKER_HOST: tcp://dockerproxy:2375
    depends_on:
      - dockerproxy
    volumes:
      - web:/config
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
    networks:
      - proxy

  sui-web:
    image: ghcr.io/carbonique/sui:1.0.0
    ports:
      - "4000:80"
    volumes:
      - web:/app/dashboard
    networks:
      - web_external

volumes:
  web:

networks:
  web_external:
  proxy:
